ls:
  .dir: snake_case | kebab-case
  .*: snake_case
  .md: snake_case | kebab-case | regex:[0-9A-Z_\-]+
  .txt: snake_case | kebab-case
  .yml: snake_case | kebab-case

ignore:
  - .git
  - .github
  - .vscode
  - venv
  - .ruff_cache
  - .pytest_cache
  - __pycache__
  - .ls-lint.yml
  - .markdownlint.yml
  - node_modules
  - .next
  - 3_webapp_development/docs
  - 3_webapp_development/app/coming-soon
  - 3_webapp_development/app/debug-auth
  - 3_webapp_development/supabase/.temp
  - 3_webapp_development/DEPLOYMENT_INSTRUCTIONS.md
  - 3_webapp_development/supabase/SETUP_GUIDE.md
